# Generated by Django 5.0.3 on 2024-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailsender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    (None, "Выберите период рассылки"),
                    ("daily", "Раз в день"),
                    ("weekly", "Раз в неделю"),
                    ("monthly", "Раз в месяц"),
                ],
                max_length=15,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    (None, "Выберите тип статуса"),
                    ("finished", "Завершена"),
                    ("created", "Создана"),
                    ("started", "Запущена"),
                ],
                max_length=15,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="status",
            field=models.CharField(
                choices=[
                    (None, "Выберите тип статуса"),
                    ("finished", "Завершена"),
                    ("created", "Создана"),
                    ("started", "Запущена"),
                ],
                max_length=15,
                verbose_name="Статус",
            ),
        ),
    ]
